#!/bin/sh

if [ -z ${FOREST_HOME+x} ]; then
  echo "No environment variable FOREST_HOME!"
  exit
fi

java -cp "$FOREST_HOME/forest-fat-4.0.0.jar" forest.App -f "$FOREST_HOME" -c presets \
-d "$FOREST_HOME/resources-bin" \
-d "$FOREST_HOME/resources-text" \
"$@"
